[IO-3] Complex command editor && Extending CM window 'reset observers' button fix
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #116
Opened 2020-06-24 12:26 UTC by Lisek8

2020-06-24 12:27 UTC, Lisek8 commented
Jędrzej Lis-Marciniak 215799
David Zientak 215934

2020-06-27 12:52 UTC, kowallus requested changes
Minor refactor left + one visitor task.

2020-06-27 12:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandEditorWindow.java
> +    private static final long serialVersionUID = 9204679248304669949L;
original code convention use tabs instead of spaces

2020-06-27 12:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandEditorWindow.java
> +    public CommandEditorWindow(DriverCommandManager commandManager) {
This method is too large. Should be divided into several separate methods

2020-06-27 12:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandEditorWindow.java
> +        } catch (ReflectiveOperationException ignored) { }
FIX: Using reflection can be replaced with better and safer OO design. In this case, visitor pattern can be used (again) to delegate a creation of a proper driverCommand.

2020-06-27 12:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandEditorWindow.java
> +    }
Please, extract this visitor to a separate class (to fix SRP).

2020-07-06 08:19 UTC, kowallus commented
poniedziałek g. 10 prezentacja?

2020-07-06 08:20 UTC, merged

2020-07-06 08:26 UTC, zenakz commented
> 
> 
> poniedziałek g. 10 prezentacja?

Ok

2020-07-06 08:31 UTC, kowallus commented
Pomyłka. Chodziło mi o środę (za dwa dni)

2020-07-06 08:35 UTC, Lisek8 commented
> Pomyłka. Chodziło mi o środę (za dwa dni)

Też ok :)

2020-07-06 08:54 UTC, kowallus commented
> > Pomyłka. Chodziło mi o środę (za dwa dni)
> 
> Też ok :)

Świetnie. Proszę przed prezentacją pobrać wszystkie zmiany z waszego grupowego repo.