IO-3 MACRO - recording driver calls as commands v2
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #30
Opened 2020-05-13 11:56 UTC by AndrzejBilant

2020-05-15 16:43 UTC, kowallus requested changes
Closer, but not enough.

2020-05-15 16:43 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/macro/MacroDriverAdapter.java
> +public class MacroDriverAdapter implements Job2dDriver {
Not right. This is decorator!

2020-05-15 16:43 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectLoadMacroListener.java
> +        driverCommand.execute(driverManager.getCurrentDriver());
If name changes from 'run' to 'load' then the logic should also be updated. Please remove it and test if it works using "Run command" from menu.

2020-05-15 16:43 UTC, kowallus commented
Reopen this PR, after modifications.

2020-05-15 16:43 UTC, closed without merging

2020-05-16 10:18 UTC, BartoszKowalczyk98 commented
We don't seem to have an option to reopen our PR.