IO-3 MACRO - recording driver calls as commands v3
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #40
Opened 2020-05-18 12:07 UTC by AndrzejBilant

Andrzej Bilant 215679
Bartosz Kowalczyk 215772

2020-05-18 12:45 UTC, AndrzejBilant commented
Poprzednie PR:
https://github.com/iis-powp-2020/powp_jobs2d_projects/pull/30
https://github.com/iis-powp-2020/powp_jobs2d_projects/pull/23

2020-05-19 06:28 UTC, kowallus requested changes
Design and functionally ok, but there are other issues.

2020-05-19 06:28 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
You changed order of imports (why?) and whitespaces in this file. Sorry, but you must revert such changes and make them according to project convention.

2020-05-19 06:28 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectLoadMacroListener.java
> +    @Override
The project uses tabs instead of spaces

2020-05-19 06:28 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectLoadMacroListener.java
> +
code duplication

2020-05-19 06:28 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectRunCurrentCommandOptionListener.java
> +import edu.kis.powp.jobs2d.features.MacroFeature;
File not reverted

2020-05-19 06:38 UTC, kowallus commented
Please test closing (and reopening) PR. By the way, think about how "Observer for a driver changes events" can be used with your feature.

2020-05-19 08:11 UTC, kowallus approved these changes
There are still some whitespaces to fix. Please, do it before merging.

2020-05-19 08:11 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/macro/MacroDriverDecorator.java
> +    private List<DriverCommand> driverCommandList;
Still spaces instead of tabs

2020-05-19 08:29 UTC, merged