deep copy complex command
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #48
Opened 2020-05-18 23:22 UTC by Thomson19

2020-05-18 23:24 UTC, Thomson19 commented
Tomasz Siekacz 215873
Bartłomiej Górkiewicz 215727

2020-05-19 07:16 UTC, kowallus requested changes
Check the issues, close PR and reopen after fixes.

2020-05-19 07:16 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICompoundCommand.java
> +		this.forEach(commands::add);
I am not sure that this is enough. You only copy references to existing commands (without making a copy). This not how cloning should look.

2020-05-19 07:16 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +		setCurrentCommand(new CompoundCommand(commandList));
Watch out: there might be conflicts with other merges (it depends on who will merge first ;) )

2020-05-19 07:16 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectDeepCopySecretCommand.java
> +
To test DEEP copy, you should have compound command embedded in another compound command.

2020-05-19 08:06 UTC, closed without merging