Deep copy of ICompoundCommand
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #50
Opened 2020-05-19 12:28 UTC by medykization

Leonard Wojtczak 215923
Damian Rutkowski 215868

2020-05-20 08:08 UTC, kowallus requested changes
Not fully correct.

2020-05-20 08:08 UTC, kowallus commented on pom.xml
> +					<target>10</target>
Is it really used?

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICompoundCommandInstance.java
> +public class ICompoundCommandInstance implements ICompoundCommand {
Class is not 'instance'. Prefix 'I' was meant to indicate the interface. 
The name should be changed (e.g. CompoundCommandImpl)

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICompoundCommandInstance.java
> +    List<DriverCommand> driverCommands;
Should be private

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICompoundCommandInstance.java
> +        List<DriverCommand> list = List.copyOf(driverCommands);
This is shallow, not a DEEP copy. Clone'ing should use a recursive approach.

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ICompoundCommand.java
> +	public ICompoundCommand clone() throws CloneNotSupportedException;
It would be best to provide a default implementation. You could use the ICompoundCommandInstance.

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ImmutableComplexCommand.java
> +        List<DriverCommand> list = List.copyOf(driverCommandList);
similar mistake

2020-05-20 08:08 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/OperateToCommand.java
> +		copy.posY = this.posY;
is it really necessary?

2020-05-20 08:08 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/ICompoundCommandListener.java
> +public class ICompoundCommandListener implements ActionListener {
The name of the listener does not indicate its purpose

2020-05-20 08:08 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/ICompoundCommandListener.java
> +        commands.add(new OperateToCommand(30, -100));
Testing DEEP copy requires a compound command embedded in another compound command (with modification of the embedded original).

2020-05-20 08:08 UTC, kowallus commented
Please close this PR and reopen after modifications

2020-05-20 13:03 UTC, medykization commented
We use ICompoundCommandImpl class and movePoint methods only for testing.

2020-05-21 09:21 UTC, kowallus requested changes
Please, avoid resigning for immutability if it is not necessary.

2020-05-21 09:21 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/ICompoundCommandDeepCopyTest.java
> +        setCommand.movePoint(20, 20);
I wouldn't like to introduce mutability to basic commands. You can provide your own mutable implementation of e.g. OperateTo and use it in test.

2020-05-21 09:21 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/SetPositionCommand.java
> +	}
Remove, please

2020-05-21 09:21 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/OperateToCommand.java
> +
create your own implementation of MutableOperateToCommand. You can do it in src/test/java.

2020-05-21 14:26 UTC, medykization commented
MutableOperateToCommand and MutableSetPositionCommand added

2020-05-25 14:19 UTC, kowallus commented
You need to resolve conflicts with the target branch before I can merge

2020-05-26 14:38 UTC, merged