IO4 - Usable commands factory
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #82
Opened 2020-06-05 11:31 UTC by kombajno678

2020-06-05 11:51 UTC, Luvkitri commented
Seems about right

2020-06-06 08:00 UTC, kowallus requested changes
Some minor issues and to many changes in DriverCommandManager makes merging impossible.

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +
Extract factory gui configuration to a separate method.

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +		currentCommandName = name;
OK. Actually 'name' should be added to the DefaultCompoundCommand (and it should be returned by toString)

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +		commandFactory.add(name, new DefaultCompoundCommand((commandList)));
No. You should not add the dependency to the commandFactory here. Use observer (see publisher)! This line should be implemented in a separate commandManager subscriber implementation.

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +	}
This also should be removed. You can call setCurrentCommand from the factory (without creating reverse dependency)

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/CommandFactory.java
> +    private HashMap<String, ICompoundCommand> shapes;
The declaration should indicate only the interface, i.e. Map.
I think that the type of values should also be more general, i.e., DriverCommand

2020-06-06 08:00 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/CommandFactory.java
> +            shapes.put(name, (DefaultCompoundCommand) commands.clone());
Is casting to DefaultCompoundCommand really important?

2020-06-06 08:00 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/features/CommandFactoryTest.java
> +                assertEquals(a1.getX(), a2.getX());
How could possibly a1 differ from a2 if they are both listOriginal.get(i)?! This part of the test does not make sense.

2020-06-06 08:00 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/features/CommandFactoryTest.java
> +        cf.add("line", icc);
You should better use constants.

2020-06-06 08:01 UTC, kowallus commented
please close, fix and reopen PR

2020-06-08 10:07 UTC, merged