Commands Transformation
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #89
Opened 2020-06-10 13:56 UTC by Patryk-97

Patryk Stępień 215886
Sebastian Pawełoszek 215844
Leonard Wojtczak 215923
Damian Rutkowski 215868

2020-06-12 13:45 UTC, kowallus requested changes
Major code duplication in the transformation manager.

2020-06-12 13:45 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandCoordinatesVisitor.java
> +	List<Line2d> lines = new ArrayList<>();
should be private

2020-06-12 13:45 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/CommandCoordinatesVisitor.java
> +	}
There shouldn't be such a visit in visitor.

2020-06-12 13:45 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/transformations/TransformationManager.java
> +	}
All methods share some code (duplication). The code is not OCP. Adding new transformation requires modification in this class (containing other transformations).

2020-06-12 13:46 UTC, kowallus commented
please close, fix and reopen

2020-06-15 15:04 UTC, Patryk-97 commented
Dzień dobry, wydaje nam się, że rozwiązaliśmy problemy, które Pan wskazał.

2020-06-16 14:45 UTC, merged