Io 3 dev history of commands
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #90
Opened 2020-06-11 14:08 UTC by 215866

2020-06-12 14:03 UTC, kowallus requested changes
Please address the following issues

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		DefaultListModel model = new DefaultListModel();
Declarations should focus on the interface (ListModel)

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/CommandHistoryController.java
> +    static DefaultListModel listModel;
should be private and focused on interface (ListModel)

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +
Do not introduce redundant CommandList (because history should work with DriverCommands, not list of commands)
Instead commandName, you should add name to CompoundCommand.

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +	}
Should be removed.

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/CommandHistoryController.java
> +    public static void addNewHistoryEntry(List<DriverCommand> commands, String name){
An entry should be a DriverCommand not a list of commands.

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		CommandHistoryController.addNewHistoryEntry(CommandsFeature.getDriverCommandManager().getCommandList(),CommandsFeature.getDriverCommandManager().getCommandName());
commandManager.runCurrentCommand() can be executed from other places. addNewHistoryEntry should be triggered by this command.

2020-06-12 14:03 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		});
Move lambda to a separate class. Maybe some dependencies can be avoided?

2020-06-12 14:03 UTC, closed without merging

2020-06-14 13:28 UTC, 215866 commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		DefaultListModel model = new DefaultListModel();
ListModel doesn't have add() method which we are using, have to stay