InkUsageMonitoring
iis-powp-2020-mbgc-backup/powp_jobs2d_projects pull request #95
Opened 2020-06-13 21:57 UTC by Blackwatch98

Considering previous comments we redeveloped our code so that the main target has been acomplished. We also wanted to add new feature like refueling ink but run into some problems with notifying (tried to repair without new publisher but it seems to be necessary). We will try to fix it before presentation if we were able to.

2020-06-15 11:13 UTC, kowallus requested changes
Some issues with the code and repo.

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/AddInkWindow.java
> +    }
this.setVisible(!this.isVisible())
:)

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/AddInkWindow.java
> +    InkUsageDriver driver;
should be private

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverManager.java
> +	private Publisher driverChange = new Publisher();
similar changes are already in the repo:
https://github.com/iis-powp-2020/powp_jobs2d_projects/pull/51/files
https://github.com/iis-powp-2020/powp_jobs2d_projects/blob/IO-2-dev/src/main/java/edu/kis/powp/jobs2d/drivers/DriverManager.java
??? Maybe something is not up to date.

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriver.java
> +public class InkUsageDriver implements Job2dDriver {
Add the name of the used design pattern to the class name.

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriver.java
> +
you should also monitor usage of a head in an inoperative state

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriver.java
> +            this.logger.info("You don't have enough ink to do this!");
it would be better to implement observer pattern here.

2020-06-15 11:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageObserver.java
> +public class InkUsageObserver implements Subscriber {
The name is confusing, because this observer does not react on ink usage state.

2020-06-17 00:29 UTC, Blackwatch98 commented
PR updated

2020-06-17 10:04 UTC, kowallus requested changes
Not yet mergable

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/AddInkWindow.java
> +    Job2dDriver driver;
Should not be private (and I am not sure if it is a good place for driver objects).

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/AddInkWindow.java
> +        InkUsageDriverAdapter cd = (InkUsageDriverAdapter) driver;
casting is a code smell in OO code. I think that there is a major issue with ISP principle (driver field).

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverChangeObserver.java
> +public class DriverChangeObserver implements Subscriber {
The name should explain the purpose of an update (not only the trigger event)

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverManager.java
> +	private Publisher publisher = new Publisher();
OK, but I wonder why I see those changes if they were already done in #51.

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriverAdapter.java
> +
Code convention in the project uses tabs not spaces!

2020-06-17 10:04 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +		//application.addWindowComponent("Add Ink", addInkWindow);
Is it fixed?

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageObserver.java
> +public class InkUsageObserver implements Subscriber {
Can it be removed now?

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriverAdapter.java
> +    private boolean bool = false;
what is bool!? The name should be better

2020-06-17 10:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/InkUsageDriverAdapter.java
> +            this.logger.info("You don't have enough ink to do this!");
Now such logger should be implemented as an observer.

2020-06-19 17:32 UTC, kowallus commented
Waiting for fixes, to give you a final project grade

2020-06-19 19:27 UTC, kowallus commented
Fixed are not really satisfactory.

2020-06-19 19:27 UTC, closed without merging

2020-06-19 19:31 UTC, Blackwatch98 commented
We haven't finished yet :D
Just pushing small changes.
We will write a comment if it's finished.